modLoader = "javafml"
loaderVersion = "${neo_version_range_supported}"
license = "MIT"
issueTrackerURL = "https://github.com/breakinblocks/BBChat/issues"

[[mods]]
modId = "bbchat"
version = "${mod_version}"
displayName = "BBChat"
displayURL = "https://github.com/breakinblocks/BBChat"
credits = "https://github.com/breakinblocks/BBChat/graphs/contributors"
authors = "BBChat contributors"
description = "Chat relay for Minecraft and Discord"

[[dependencies.bbchat]]
modId = "forge"
mandatory = true
versionRange = "${neo_version_range_supported}"
ordering = "AFTER"
side = "BOTH"

[[dependencies.bbchat]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range_supported}"
ordering = "AFTER"
side = "BOTH"
